{
 "title": "Golang Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(go_info,job)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(process_network_receive_bytes_total{job=\"$job\"}[5m]))",
     "legendFormat": "input"
    },
    {
     "expr": "sum by(job) (rate(process_network_transmit_bytes_total{job=\"$job\"}[5m]))",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"} / go_gc_gomemlimit_bytes{job=\"$job\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input network",
   "type": "stat",
   "description": "Входящий сетевой трафик в минуту",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Value, instance) (rate(process_network_receive_bytes_total{job=\"$job\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Network",
   "type": "stat",
   "description": "Исходящий сетевой трафик",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Value, instance) (rate(process_network_transmit_bytes_total{job=\"$job\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "used memory / {{ job }}"
    },
    {
     "expr": "go_gc_gomemlimit_bytes{job=\"$job\"}",
     "legendFormat": "memory limit / {{ job }}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in Stack",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=\"$job\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{job=\"$job\"}",
       "legendFormat": "__auto"
      },
      {}
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory in Heap (objects)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_memstats_heap_objects{job=\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OS Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "go_threads{job=\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"$job\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{job=\"$job\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{job=\"$job\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"$job\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "go_memstats_heap_released_bytes{job=\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{job=\"$job\"} - go_memstats_frees_total{job=\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC duration pauses in minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_sum{job=\"$job\"}[1m])"
      }
     ]
    }
   ]
  }
 ]
}